function initDefaultMeters(sheet) {
  const defaults = [
    ['WM-01',"การประปาด้านหน้าโรงงาน (การประปา MWA) [8\"]",'RAWWATER','m3',0,1],
    ['WM-02',"การประปาข้าง Store Tooling (การประปา MWA) [6\"]",'RAWWATER','m3',0,1],
    ['WM-03',"ประปาหน้าโรงงานเข้าบ่อ 500 Tons [4\"]",'RAWWATER','m3',0,1],
    ['WM-04',"ประปาข้างโรงงานเข้าบ่อ 500 Tons [6\"]",'RAWWATER','m3',0,1],
    ['WM-05',"ประปาจากบ่อ 500 Tons เข้า Paint Shop [8\"]",'PAINT','m3',0,1],
    ['WM-06',"ประปาจาก 500 Tons ไป DI & WWT Plant [3\"]",'ROWWT','m3',0,1],
    ['WM-07',"Main การประปาเข้าบ่อ 180 T. New Office [4\"]",'OFFICE','m3',0,1],
    ['WM-08',"Main Header ประปาบ่อ 150 T. ไปด้านหลัง LA, UA, FR, KD, KZ [3\"→5\"]",'PAINT','m3',0,1],
    ['WM-09',"Main ประปาเข้าโรงประกอบ ASS'Y (UA) [4\"]",'UA','m3',0,1],
    ['WM-10',"ประปาเข้า Shower Test ASS'Y (LA) [2\"]",'LA','m3',0,1],
    ['WM-11',"ประปาที่ใช้กับร้านค้า Canteen [1.5\"]",'CANTEEN','m3',0,1],
    ['WM-12',"เมนประปาจ่ายไปโรงอาหาร Assy [3\"]",'CANTEEN','m3',0,1],
    ['WM-13',"จาก Header UA ไป Air Supply PT-7, PT-8 [1\"]",'PT78','m3',0,1],
    ['WM-14',"จาก Header UA ไป Old Office & UA Shop [4\"]",'UA','m3',0,1],
    ['WM-15',"Main ประปาหน้าโรงงานเข้า Cooling Tower Body Shop [2\"]",'BODY','m3',0,1],
    ['WM-16',"Main Header ประปา 150 Tons ไป Body Shop [3\"]",'BODY','m3',0,1],
    ['WM-17',"ประปาจาก 150 Tons ไปโรงอาหาร Body [1\"]",'BODY','m3',0,1],
    ['WM-18',"Cooling Spot Line 190 (70 T.) [2\"]",'BODY','m3',0,1],
    ['WM-19',"ประปาเติมน้ำดิบ RO Plant [2\"]",'ROWWT','m3',0,1],
    ['WM-20',"Cooling Tower Chiller Daikin [2\"]",'UTILCOOL','m3',0,1],
    ['WM-21',"น้ำ RO เข้า Skid Cleaning House [2\"]",'UTILCOOL','m3',0,1],
    ['WM-22',"Main Header ประปา 150 Tons ไป WWT Plant [3\"]",'ROWWT','m3',0,1],
    ['WM-23',"ประปา 150 Tons ไป Frame Shop [3\"]",'FRAME','m3',0,1],
    ['WM-24',"ประปาจาก 150 Tons ไป Shower Test FR Shop [2\"]",'FR','m3',0,1],
    ['WM-25',"New Office Canteen ชั้น 7 (180 Tons) [1\"]",'OFFICE','m3',0,1],
    ['WM-26',"ประปาเติม Shower Test FR Shop [2\"]",'FR','m3',0,1],
    ['WM-27',"ประปาหลังโรงงานเข้า Skid Cleaning House [2\"]",'UTILCOOL','m3',0,1],
    ['WM-28',"การประปาหลังโรงงาน (การประปา MWA) [1\"]",'RAWWATER','m3',0,1],
    ['WM-29',"ประปา 150 Tons ไป KD, KZ, Frame, โรงจอดรถ [3\"]",'FRAME','m3',0,1],
    ['WM-30',"ประปาเติม Cooling Tower Tasaki ED [2\"]",'UTILCOOL','m3',0,1],
    ['WM-31',"ประปาเติม Cooling Tower Tasaki Air Supply",'UTILCOOL','m3',0,1],
    ['WM-32',"RO Water เติม Cooling Tower Air Compressor [2\"]",'UTILCOOL','m3',0,1],
    ['WM-33',"Booth พ่นสีใหม่ PT-7 [2\"]",'PT78','m3',0,1],
    ['WM-34',"ห้องน้ำ Frame [1\"]",'FRAME','m3',0,1],
    ['WM-35',"ประปาห้องน้ำลานจอดรถ OK [1\"]",'SEPTIC','m3',0,1],
    ['WM-36',"Treated Water ไปที่ Belts Press [3\"]",'ROWWT','m3',0,1],
    ['WM-37',"Treated Water ส่งเข้า RO Plant [4\"]",'ROWWT','m3',0,1],
    ['WM-38',"Treated Water เติมรถธุรการ [2\"]",'ROWWT','m3',0,1],
    ['WM-39',"Main ประปา 8 ไร่ (การประปา MWA) [2\"]",'RAWWATER','m3',0,1],
    ['WM-40',"Toilet Water ส่งเข้า Septic Plant [4\"]",'SEPTIC','m3',0,1],
    ['WM-41',"ประปาจ่าย Air Supply PT-7 [1.5\"]",'PT78','m3',0,1],
    ['WM-42',"ประปาหลังคา UA จ่ายไป PT-7, PT-8 [2\"]",'PT78','m3',0,1],
    ['WM-43',"ประปาหน้าโรงงานเข้าห้องน้ำ Body [2\"]",'BODY','m3',0,1],
    ['WM-44',"Cooling Chiller ED Frame [1\"]",'FRAME','m3',0,1],
    ['WM-45',"น้ำรีไซเคิลด้านหลัง WWT Plant [1.5\"]",'ROWWT','m3',0,1],
    ['WM-46',"Recycle Water Body Shop (From Septic) [8\"]",'BODY','m3',0,1],
    ['WM-47',"Recycle Water Office (From Septic) [1.5\"]",'OFFICE','m3',0,1],
    ['WM-48',"น้ำประปาเข้า Septic Plant [2\"]",'ROWWT','m3',0,1],
    ['WM-49',"ประปาเติมเคมี WWT Plant [2\"]",'ROWWT','m3',0,1],
    ['WM-50',"Recycle Water รดน้ำต้นไม้ข้างห้องสี",'PAINT','m3',0,1],
    ['WM-51',"ประปา 150 Tons เข้า Ass'y Shop",'LA','m3',0,1],
    ['WM-52',"ประปาเข้าห้องน้ำ UA Shop",'UA','m3',0,1],
    ['WM-53',"RO Water เข้า Shower Test (FR Shop) [6\"]",'FR','m3',0,1],
    ['WM-54',"RO Water เข้า Shower Test (LA Shop) [2\"]",'LA','m3',0,1],
    ['WM-55',"RO Water เข้า Cooling Tank (Body Shop) [2\"]",'BODY','m3',0,1],
    ['WM-56',"RO Water เข้า Cooling Frame Shop [1\"]",'FRAME','m3',0,1],
    ['WM-57',"RO Water เข้า Shower Test (Audit Shop) [1½\"]",'FR','m3',0,1],
    ['WM-58',"RO Water เข้า Cooling Tower Daikin No.3-4 (Power Zone) [1½\"]",'POWERZONE','m3',0,1],
    ['WM-59',"Cooling E.D [1\"]",'UTILCOOL','m3',0,1],
    ['WM-60',"Main ประปาเข้า New Septic (การประปา MWA) [1½\"]",'RAWWATER','m3',0,1],
  ];
  sheet.getRange(2, 1, defaults.length, 6).setValues(defaults);
}

function initDefaultReportGroups(sheet) {
  const rows = [
    ['BODY',      'Body Shop',        '🏭', '#00D4FF', 'main', 'WM-15,WM-16,WM-17,WM-18,WM-43,WM-46,WM-55', ''],
    ['PT78',      'PT7-8',            '🏗️', '#a78bfa', 'main', 'WM-13,WM-33,WM-41,WM-42', ''],
    ['PAINT',     'Paint Shop',       '🎨', '#22C55E', 'main', 'WM-05,WM-08', 'WM-24,WM-29'],
    ['CANTEEN',   'Canteen',          '🍽️', '#FACC15', 'main', 'WM-11,WM-12', ''],
    ['LA',        'LA',               '🔧', '#fb923c', 'main', 'WM-10,WM-51', 'WM-24,WM-29'],
    ['FRAME',     'Frame',            '🔩', '#f472b6', 'main', 'WM-23,WM-34,WM-44,WM-56', ''],
    ['UA',        'UA',               '⚙️', '#38bdf8', 'main', 'WM-09,WM-14,WM-52', ''],
    ['OFFICE',    'Office',           '🏢', '#818cf8', 'main', 'WM-07,WM-25,WM-47', ''],
    ['FR',        'FR Shop',          '🚧', '#fb7185', 'main', 'WM-24,WM-26,WM-29', ''],
    ['POWERZONE', 'Power Zone',       '⚡', '#f59e0b', 'main', 'WM-58', ''],
    ['RAWWATER',  'Raw Water Supply', '🚰', '#06b6d4', 'main', 'WM-01,WM-02,WM-03,WM-04,WM-28,WM-39,WM-60', ''],
    ['ROWWT',     'RO/WWT/DI Plant',  '♻️', '#14b8a6', 'main', 'WM-06,WM-19,WM-22,WM-36,WM-37,WM-38,WM-45,WM-48,WM-49', ''],
    ['UTILCOOL',  'Utility/Cooling',  '❄️', '#60a5fa', 'main', 'WM-20,WM-21,WM-27,WM-30,WM-31,WM-32,WM-59', ''],
    ['SEPTIC',    'Toilet/Septic',    '🚻', '#a3a3a3', 'main', 'WM-35,WM-40', '']
  ];
  sheet.getRange(2, 1, rows.length, GROUP_HEADERS.length).setValues(rows);
}